### ISSUE TITLE
Gitignore key

### ISSUE THREAD

**Issue by forki** [mikhailshilkov/tictactoe#1]
https://github.com/mikhailshilkov/tictactoe/blob/master/TicTacToe.Functions/local.settings.json#L4 <- I hope that key is not important...

**Comment by mikhailshilkov** [comment]
Thanks for letting me know. It's not important, I changed the string and I'll kill this account later on.

**Comment by forki** [comment]
tried to send it as DM on twitter but you don't follow me ;-)

**Comment by mikhailshilkov** [comment]
Also fixed :)
