### ISSUE TITLE
How to publish the functions

### ISSUE THREAD

**Issue by forki** [mikhailshilkov/tictactoe#2]
I tried to convert a function from function.json style to https://github.com/mikhailshilkov/tictactoe/blob/master/TicTacToe.Functions/Functions.fs#L53, but after CLI push it doesn't show anymore in the portal!? Any ideas?

**Comment by mikhailshilkov** [comment]
Are you running publish command from root folder with `fsproj` or from `publish` folder? I've seen the former "succeed" but with 0 functions published.

**Comment by forki** [comment]
I'm copying everything into a publish folder and call cli from there.

**Comment by mikhailshilkov** [comment]
Do you see `function.json` in function subfolders in `publish` folder? Do you see the same in Kudu after publishing?

**Comment by forki** [comment]
Thank you. looking into generated function.json was indeed helpful. It's using a different path. 
![image](https://user-images.githubusercontent.com/57396/35384048-643d8dc6-01c4-11e8-9dcb-913d3e3b6371.png)

It looks like the path is actually wrong when you use dotnet publish.
Anyway I changed my deploy script to massage the function.json accordingly and it's working now. 
Many thanks.

**Comment by mikhailshilkov** [comment]
The path looks ok to me, it resembles the structure that I get from `dotnet publish` (`bin` on the same level as function folders).

**Comment by forki** [comment]
yes structure just changed. I'm trying to update my script accordingly. thanks

**Comment by forki** [comment]
![functionapp](https://user-images.githubusercontent.com/57396/35386252-af4a757a-01cb-11e8-9fae-251bbb396d33.png)

do you run publish from that folder? It doesn't show anything in portal for me
