### ISSUE TITLE
Dependency on MVC

### ISSUE THREAD

**Issue by forki** [mikhailshilkov/tictactoe#3]
Things like https://github.com/mikhailshilkov/tictactoe/blob/master/TicTacToe.Functions/Functions.fs#L37 depend on MVC - that's really really weird. Since we don't use MVC - can we move these helpers to somewhere else?

**Comment by mikhailshilkov** [comment]
IActionResult, ContentResult, ObjectResult etc are defined in MVC. And since that's the suggested way for v2, you should rather ask on Functions repositories.

**Comment by forki** [comment]
moved to https://github.com/Azure/Azure-Functions/issues/671
